### ISSUE TITLE
istio-keycloak-demo on kubernetes

### ISSUE THREAD

**Issue by cdelpinogeo** [kameshsampath/istio-keycloak-demo#6]
Hi @kameshsampath,

We had a play with your project and wanted to know if anyone has been able to take what you did and implement this on a Kubernetes platform that is not OpenShift? We have a Kubernetes cluster running on AWS deployed using kops, so some of the yaml files do not work as they are specific to OpenShift.

**Comment by kameshsampath** [comment]
hi @cdelpinogeo  -  ideally this should run on any kubernetes platform as i have not used any thing specific to OpenShift.  are you facing any issues ?

To answer straight to your question - i dont know anyone who has did that.

**Comment by cdelpinogeo** [comment]
Hi @kameshsampath - I needed to make modifications to the manifests as they won't work in our Kubernetes cluster in their current format. Here is how I changed keycloak.yaml to deploy on k8s:

```
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations: {}
    labels:
      app: keycloak
    name: keycloak-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: keycloak
    annotations:
      sidecar.istio.io/inject: "false"
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: keycloak
      spec:
        securityContext:
          fsGroup: 1000
        containers:
        - name: keycloak
          image: docker.io/jboss/keycloak:3.4.3.Final
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: KEYCLOAK_USER
            value: admin
          - name: KEYCLOAK_PASSWORD
            value: admin
          livenessProbe:
            httpGet:
              path: /auth
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /auth
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 10
          volumeMounts:
          - mountPath: /opt/jboss/keycloak/standalone/data
            name: keycloak-data
            readOnly: false
        volumes:
        - name: keycloak-data
          persistentVolumeClaim:
            claimName: keycloak-data
- apiVersion: v1
  kind: Service
  metadata:
    name: keycloak
  spec:
    ports:
    - name: http
      port: 8080
    type: LoadBalancer
    selector:
      app: keycloak
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    labels:
      expose: "true"
      app: keycloak
    name: keycloak
  spec:
    backend:
      serviceName: keycloak
      servicePort: 8080
```
I do have some more questions as I am not deploying this as per your instructions due to differing environments:

1. Prior to deploying the cars app, there is a command you mention to run:
```
oc adm policy add-scc-to-user privileged -z default -n <your project>
```
is this specific to OpenShift or is there a similar way to run this using kubectl?

2. I deployed a modified version of istio-cars-api-0.0.1.yml:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: cars-api
    version: 0.0.1
  name: cars-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cars-api
  strategy: {}
  template:
    metadata:
      annotations:
      labels:
        app: cars-api
        version: 0.0.1
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: kameshsampath/cars-api:1.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 180
        name: spring-boot
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
        resources: {}
        securityContext:
          privileged: false
      - args:
        - proxy
        - sidecar
        - -v
        - "2"
        - --configPath
        - /etc/istio/proxy
        - --binaryPath
        - /usr/local/bin/envoy
        - --serviceCluster
        - cars-api
        - --drainDuration
        - 45s
        - --parentShutdownDuration
        - 1m0s
        - --discoveryAddress
        - istio-pilot.istio-system:15003
        - --discoveryRefreshDelay
        - 1s
        - --zipkinAddress
        - zipkin.istio-system:9411
        - --connectTimeout
        - 10s
        - --statsdUdpAddress
        - istio-mixer.istio-system:9125
        - --proxyAdminPort
        - "15000"
        - --controlPlaneAuthPolicy
        - NONE
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: docker.io/istio/proxy_debug:0.4.0
        imagePullPolicy: IfNotPresent
        name: istio-proxy
        resources: {}
        securityContext:
          privileged: true
          readOnlyRootFilesystem: false
          runAsUser: 1337
        volumeMounts:
        - mountPath: /etc/istio/proxy
          name: istio-envoy
        - mountPath: /etc/certs/
          name: istio-certs
          readOnly: true
      initContainers:
      - args:
        - -p
        - "15001"
        - -u
        - "1337"
        image: docker.io/istio/proxy_init:0.4.0
        imagePullPolicy: IfNotPresent
        name: istio-init
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
      - args:
        - -c
        - sysctl -w kernel.core_pattern=/etc/istio/proxy/core.%e.%p.%t && ulimit -c
          unlimited
        command:
        - /bin/sh
        image: alpine
        imagePullPolicy: IfNotPresent
        name: enable-core-dump
        resources: {}
        securityContext:
          privileged: true
      volumes:
      - emptyDir:
          medium: Memory
          sizeLimit: "0"
        name: istio-envoy
      - name: istio-certs
        secret:
          optional: true
          secretName: istio.default
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    expose: "true"
    app: cars-api
    version: 0.0.1
  name: cars-api
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: cars-api
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    expose: "true"
    app: cars-api
    version: 0.0.1
  name: cars-api
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: cars-api
          servicePort: 8080
---
```
and I also deployed car-api-auth_config.yaml and mixer-rule-only-authorized.yaml. Do the other files under cars-api/src/istio/ need to be deployed?

3. I started to test this by testing without a token:
```
curl -vvv $(minishift openshift service cars-api)/cars/list
```
is `minishift openshift service cars-api` actual service for cars api or the ingress?
